sfdx-project/force-app/main/default/objects/Developer_Log__c/Developer_Log__c.object-meta.xml
<CustomObject>
    <description>Holds informative or error logs for developers to have better information about running processes.</description>
    <label>Developer Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developer Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-project/force-app/main/default/objects/Developer_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>A complete message describing the log</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-project/force-app/main/default/objects/Developer_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The log type: whether it&apos;s informative, a warning or an error.</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>WARNING</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-project/force-app/main/default/classes/DeveloperLogHandler.cls
/*
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* DeveloperLogHandler: Handler for working with Developer_Log__c records
*
*   Handler class to outsource logic having to do with logging information or errors into
*   Developer_Log__c records, and keep calling classes simplified.
*
* Constructor: No constructor
*
* Methods:
*     - public static void createDevLog(
*           DeveloperLogHandler.LogType type, String name, String message
*       )
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Federico Abella   <federico.abella@cloudgaia.com>
* @modifiedBy     Federico Abella   <federico.abella@cloudgaia.com>
* @maintainedBy   Federico Abella   <federico.abella@cloudgaia.com>
* @version        1.0
* @created        2022-06-14
* @modified       2022-06-14
* @systemLayer    Utility
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public class DeveloperLogHandler {
    
    public Enum LogType {INFO, WARNING, ERROR}

    public static void createDevLog(LogType type, String name, String message){
        insert new Developer_Log__c(
            Name = name,
            Type__c = type.name(),
            Message__c = message
        );
    }
}