sfdx-project/force-app/main/default/objects/Developer_Log__c/Developer_Log__c.object-meta.xml
<CustomObject>
    <description>Holds informative or error logs for developers to have better information about running processes.</description>
    <label>Developer Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developer Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-project/force-app/main/default/objects/Developer_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>A complete message describing the log</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-project/force-app/main/default/objects/Developer_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The log type: whether it&apos;s informative, a warning or an error.</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>WARNING</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-project/force-app/main/default/classes/DeveloperLogHandler/DeveloperLogHandlerTest.cls
/*
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* DeveloperLogHandlerTest: Test class for testing the DeveloperLogHandler class
*
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Federico Abella   <federico.abella@cloudgaia.com>
* @modifiedBy     Federico Abella   <federico.abella@cloudgaia.com>
* @maintainedBy   Federico Abella   <federico.abella@cloudgaia.com>
* @version        1.0
* @created        2022-06-25
* @modified       2022-06-25
* @systemLayer    Test
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
@isTest
private class DeveloperLogHandlerTest {
    
    /*
    * Test creating an error log using the DeveloperLogHandler class
    */
    @IsTest
    static void testCreateLog(){
        
        Test.startTest();
            DeveloperLogHandler.createDevLog(
                DeveloperLogHandler.LogType.ERROR, 
                'Test Log', 
                'Some error happened and this is a log for it'
            );
        Test.stopTest();

        List<Developer_Log__c> logsList = [
            SELECT Name, Type__c, Message__c
            FROM Developer_Log__c
        ];

        System.assertEquals(1, logsList.size());
        System.assertEquals('ERROR', logsList[0].Type__c);
        System.assertEquals('Test Log', logsList[0].Name);
        System.assertEquals(
            'Some error happened and this is a log for it', 
            logsList[0].Message__c
        );
    }
}